title: Stephen Czekalski
email: admin@stephencz.com
description: The personal website of Stephen Czekalski. A place for me to store my writings and works on the topics which interest me.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.stephencz.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stephencz
github_username:  stephencz

permalink: /posts/:title

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      reading_time: 0
      word_count: 0
      toc: true
      excerpt_separator: <!--more-->

  -
    scope:
      path: ""
      type: "pages"
    values:
      is_page: true
      toc: true

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

scholar:
  style: _bibliography/apa
  locale: en

  sort_by: author, year, month, day
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }}"

  reference_tagname: "p"

  replace_strings: true
  join_strings:    true

  bibtex_filters:
    - href

  query: "@*"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-scholar

exclude:
  - /scripts
  - /vendor
  - /screenshot.png
  - /README.md
  - /LICENSE
  - /Gemfile
  - /Gemfile.lock
  - node_modules
  - .vendor/bundle/
  - .vendor/cache/
  - .vendor/gems/
  - .vendor/ruby/
